[build]
dist = "../../dist/arrow-blocks"
public_url = "."

[[hooks]]
stage = "pre_build"
command = "sh"
command_arguments = [
  "-c",
  """
set -e
cargo build --target wasm32-unknown-unknown --release --bin arrow-blocks --manifest-path ../../Cargo.toml
mkdir -p vendor
[ -f vendor/mq_js_bundle.js ] || curl -sSfL https://not-fl3.github.io/miniquad-samples/mq_js_bundle.js -o vendor/mq_js_bundle.js
""",
]
